global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'monitoring_backend'
    static_configs:
      - targets: ['backend:8001']

  - job_name: 'endpoints'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']